import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/header";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en">
			<Providers>
				<body>
					<Header session={session} />
					<main>{children}</main>
				</body>
			</Providers>
		</html>
	);
}
